name: taxonetime
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  rive: ^0.8.1
  firebase_core: ^1.11.0
  # flutter_easyloading: ^3.0.3
  video_player: ^2.2.10
  shared_preferences: ^2.0.11
  get: ^4.6.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.3
  sign_button: ^2.0.2
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  url_launcher: ^6.0.18
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1
  sign_in_with_apple: ^3.3.0
  flutter_spinkit: ^5.1.0
  email_validator: ^2.0.1
  flutter_pw_validator: ^1.3.0
  font_awesome_flutter: ^9.2.0
  crypto: ^3.0.1
  dialog_flowtter: ^0.3.1
  dialogflow_flutter: ^1.0.0
  equatable: ^2.0.3
  intl: ^0.17.0
  bubble: ^1.2.1
  persistent_bottom_nav_bar: ^4.0.2
  carousel_slider: ^4.0.0
  news_api_flutter_package: ^1.1.0
  image_picker: ^0.8.4+11
  timelines: ^0.1.0
  flutter_mobile_vision: ^0.1.3
  ar_flutter_plugin: ^0.6.2
  cnic_scanner: ^0.0.2
  getwidget: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  branding: "assets/icons/brand1.png"
  branding_mode: bottom
  image: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/dialog_flow_auth.json
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/swiper/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
          weight: 300
